export default {
    bgImage:require('../assets/images/bg.png'),
    logo:require('../assets/images/logo/logo.png'),
    whiteLogo:require('../assets/images/logo/whiteLogo.png'),
    filterIcon:require('../assets/images/icons/filterIcon.png'),
    home:require('../assets/images/icons/home.png'),
    notify:require('../assets/images/icons/notify.png'),
    star:require('../assets/images/icons/star.png'),
    share:require('../assets/images/icons/share.png'),
    support:require('../assets/images/icons/support.png'),
    qna:require('../assets/images/icons/qna.png'),
    terms:require('../assets/images/icons/terms.png'),
    about:require('../assets/images/icons/about.png'),
    plusIcon:require('../assets/images/icons/plusIcon.png'),
    location:require('../assets/images/icons/location.png'),
    backIcon:require('../assets/images/icons/back.png'),
    image:require('../assets/images/icons/image.png'),
    emergency:require('../assets/images/CategoryIcons/emergency.png'),
    medical: require('../assets/images/CategoryIcons/medical.png'),
    giveAwayItem: require('../assets/images/CategoryIcons/giveAway.png'),
    social: require('../assets/images/CategoryIcons/social.png'),
    roadAssist:require('../assets/images/CategoryIcons/roadAssist.png'),
    ride: require('../assets/images/CategoryIcons/ride.png'),
    lostAndFound: require('../assets/images/CategoryIcons/lost.png'),
    itemNeeded: require('../assets/images/CategoryIcons/itemNeeded.png'),
    general: require('../assets/images/CategoryIcons/general.png'),
    time:require('../assets/images/icons/time.png'),
    mapIcon:require('../assets/images/icons/mapIcon.png'),
    distance:require('../assets/images/icons/distance.png'),
    delete:require('../assets/images/icons/delete.png'),
    lock:require('../assets/images/icons/lock.png'),
    edit:require('../assets/images/icons/edit.png'),
    posterIcon:require('../assets/images/icons/posterIcon.png'),
    call:require('../assets/images/icons/call.png'),
    calender:require('../assets/images/icons/calender.png'),
    urgencyLevel:require('../assets/images/icons/urgency.png'),
    whatsApp:require('../assets/images/icons/whatsApp.png'),
    dialer:require('../assets/images/icons/dialer.png'),
    message:require('../assets/images/icons/message.png'),
    inActiveSwitch:require('../assets/images/icons/switchInActive.png'),
    activeSwitch:require('../assets/images/icons/switchActive.png'),
    check:require('../assets/images/icons/check.png'),
    successIcon:require('../assets/images/icons/successIcon.png'),
    hamburgerMenuIcon:require('../assets/images/icons/hamburger_menu_icon.png'),
    dropDownIcon:require('../assets/images/icons/dropDownIcon.png'),

}