export default {
login:'Login',
verifyOtp:'verifyOtp',
welcomeScreen:'welcomeScreen',
home:'Home',
notification:'Notifications',
terms:'Terms of use',
helpCenter:'Help Center',
about:'About',
qna:'QnA',
newRequestMain:'New Request',
filter:'Filter',
postDetails:'Post Details',
requestDetails:'Request Details',
location:'Location',
category:'Category',
keywords:'Keywords',
quiteHours:'Quite hours',
}