export default {
    MOBILE_NUMBER: 'Mobile Number',
    NXT: 'NEXT',
    VERIFICATION_CODE: 'Verification Code',
    ENTER_VERIFICATION_CODE: 'Please enter the SMS verification \ncode sent to you',
    WELCOME_TO_WILLING: 'Welcome To Willing',
    CONGRATS_YOU_VERIFIED: 'Congratulations you’re \nverified!',
    aboutDescription: `אפליקציה חברתית המחברת בין אנשים הזקוקים לעזרה כלשהי לאלה שיכולים לסייע. החיבור באמצעות מנוע חכם המשתמש בפרטים שנמסרו על ידי המשתמשים כדי לייצר התאמות אפקטיביות.`,
    aboutTitle: `About Willing`,
    aboutTitleUpperCase: `ABOUT`,
    appVerErrorMessage: `Oops! It seems your application is out of date, Update the application to keep using it`,
    call: `Call`,
    cancel_uppercase: `CANCEL`,
    close: `Close`,
    closeNote: `Are you sure you want to close the request? In this status, other users could not see the request`,
    contactUs_email: `E-MAIL`,
    contactUs_EmailHint: `ex: your@email.com`,
    contactUs_error_email: `Email must be in right format, example@example.com`,
    contactUs_error_message: `Enter a message`,
    contactUs_error_name: `Enter your full name`,
    contactUs_error_phone: `Phone must be in right format`,
    contactUs_fullName: `FULL NAME`,
    contactUs_fullNameHint: `ex: Israel Israeli`,
    contactUs_message: `MESSAGE`,
    contactUs_messageHint: `Enter your message here…`,
    contactUs_phone: `PHONE`,
    contactUs_phoneHint: `ex: 0501234567`,
    contactUs_title: `Having trouble? Do you have a question? You just want to say something? We are here for you (:`,
    contactUsSuccess: `Thanks for your message`,
    defaultMessageForUser: `Hello, I saw your post on Willing:\n \n [Desc]\n \n  I\'d be happy to help if I can.\n  www.willingapp.com`,
    delete: `Delete`,
    deletedMessage: `Your request was deleted`,
    deleteNote: `Are you sure you want to Delete this request? This action can\'t be undone`,
    description_uppercase: `DESCRIPTION`,
    distance_uppercase: `DISTANCE FROM YOU`,
    dueDate_uppercase: `EXPIRES IN`,
    edit_lowercase: `Edit`,
    edit_uppercase: `EDIT`,
    editRequest_title: `EDIT REQUEST`,
    Emergency: `Emergency`,
    filter_byKeyword: `Filter by keyword`,
    filter_clear: `Clear`,
    filter_missingData: `No requests were found for the data you entered`,
    filter_pickCategory: `Pick category`,
    filter_pickCity: `Pick city`,
    filter_title: `Filter`,
    fullImage_image: `Image`,
    fullImage_of: `of`,
    General: `General`,
    GiveAwayItem: `Give Away Item`,
    gpsDeniedNote: `For full experience of the app you should be given location permissions`,
    image_pickerOptions: `Pick option`,
    image_uppercase: `IMAGE`,
    imageLink_uppercase: `IMAGE LINK`,
    informationNotAvailable: `Information not available`,
    intro_description1: `Request what you need from relevant people who want to help`,
    intro_description2: `Got Help? You can close the request so no-one bothers you anymore`,
    intro_description3: `Want to help someone? You choose who and when`,
    intro_title1: `Get Help`,
    intro_title2: `Control over requests`,
    intro_title3: `Micro-volunteering`,
    ItemNeeded: `Item Needed`,
    location_setLocation: `Set Location`,
    location_uppercase: `LOCATION`,
    LostAndFound: `Lost And Found`,
    Medical: `Medical`,
    message: `Message`,
    messageBar_tip1: `You can always close the request by entering your own request and clicking \"Close\".`,
    messageBar_tip2: `Know someone who needs help? Open a request on their behalf using their city and phone number.`,
    messageBar_tip3: `Did you know? Willing is not for profit. You\'re welcome to volunteer with us or donate. Contact us using the side options.`,
    messageBar_tip4: `We\'re always happy to get comments or ideas for improvement. Contact us using the side options.`,
    messageBar_tip5: `Coming soon: anonymous chat, smart push notifications and a clever filter: You decide when to get requests, where and what kind.`,
    mineTag: `Mine`,
    moreInfo: `Show more info`,
    name: `Name`,
    name_uppercase: `NAME`,
    nav_about: `About`,
    nav_faq: `FAQ`,
    nav_feedback: `Help/Feedback`,
    nav_homeScreen: `Home Screen`,
    nav_RateUs: `Rate Us`,
    nav_settings: `Settings`,
    nav_Share: `Share`,
    nav_terms_n_conditions: `Terms and conditions`,
    networkErrorMessage: `Oops! An Internet connection is required to use the application`,
    networkErrorTitle: `No Connection`,
    newRequest_categoriesDescription: `Let’s start by choosing a category that best describes your request. This helps other people to notice your request quickly.`,
    newRequest_contactDescription: `We\'re almost set! Fill out your details or the person on whose behalf you\'re setting up the request`,
    newRequest_contactOptionMyDetails: `My details`,
    newRequest_contactOptionSomeoneElse: `Someone else`,
    newRequest_contactsPicker: `Choose from your contacts list`,
    newRequest_detailsDescription: `" Now fill in details regarding your request "`,
    newRequest_detailsDescriptionHint: `Enter request description with min. 20 characters`,
    newRequest_successMessage: `Your request posted successfully`,
    newRequest_successUpdate: `Your request Updated successfully`,
    newRequest_title: `NEW REQUEST`,
    newRequest_whenDescription: `Until when to post?`,
    newRequest_whereDescription: `What radius from the location should this be posted?`,
    newRequestLocation: `LOCATION (DEFAULT - CURRENT)`,
    next_uppercase: `NEXT`,
    no: `No`,
    noDataMessage_mine: `You haven\'t made any requests, so the screen is blank, to make a new request, press + down.`,
    noPermission: `No Permission`,
    noString: `N/A`,
    ok_uppercase: `OK`,
    phone: `Phone Number`,
    phone_uppercase: `PHONE NUMBER`,
    posted: `Recently posted`,
    postedForOtherMessage: `Hello, I\'ve posted your request on Willing:\n\n[fullDesc]\n\nI hope for help, if you someone helped you, I\'d be happy for an update and I\'ll close the request at the application.\n\nThe application is here: [http://www.willingapp.com].\nGood Luck (:`,
    posterName_uppercase: `POSTER NAME`,
    report: `Report this request`,
    reportHint: `Write your note…`,
    reportNote: `Why you want to report this request?`,
    reportSuccess: `Report sent successfully, thank you for your vigilance`,
    requestDetails_CallTo: `Call To:`,
    requestDetails_CallToError: `Can\'t call, missing number`,
    requestDetails_connectionDetails: `You can contact the publisher in the following ways:`,
    requestDetails_km: `km`,
    requestDetails_meter: `m`,
    requestDetails_SMSError: `Can\'t send SMS, missing number`,
    requestDetails_title: `REQUEST DETAILS`,
    requestDetails_whatsApp: `WhatsApp`,
    requestLink_uppercase: `REQUEST LINK`,
    RideDeliver: `Ride/Deliver`,
    RoadAssist: `Road Assist`,
    send: `Send`,
    sendFailure: `Something wrong, your request was not sent, please try again`,
    serverConnectionErrorMessage: `Oops! It\'s seems to be problems with the server, please try later`,
    settings_language: `Language`,
    settingsNotification: `Notification Settings`,
    settingsNotification_addToList: `Add to list`,
    settingsNotification_category: `Category`,
    settingsNotification_categoryDesc: `All categories`,
    settingsNotification_categoryError: `Emergency request cannot be disabled`,
    settingsNotification_categoryInnerDesc: `Choose about which categories you will want to get notifications`,
    settingsNotification_emptyAppendError: `Write in the appropriate field`,
    settingsNotification_keywords: `Keywords`,
    settingsNotification_keywordsAppendError: `The keyword is already in the list`,
    settingsNotification_keywordsDesc: `Set requests by keywords`,
    settingsNotification_keywordsHint: `Enter keyword`,
    settingsNotification_keywordsInnerDesc: `Send notification if the following words appears inside the request`,
    settingsNotification_location: `Location`,
    settingsNotification_locationDesc: `From everywhere`,
    settingsNotification_main: `Enable notifications`,
    settingsNotification_mainDesc: `Send notifications about new requests`,
    settingsNotification_quietHours: `Quiet hours`,
    settingsNotification_quietHoursDesc: `Set hours when no notifications will be received`,
    settingsNotificationLocation_alsoFrom: `And also from`,
    settingsNotificationLocation_cityAppendError: `The city is already in the list`,
    settingsNotificationLocation_cityDesc: `Enter a city name from which you would like to receive alerts`,
    settingsNotificationLocation_cityHint: `Enter city name`,
    settingsNotificationLocation_cityTitle: `Specific city`,
    settingsNotificationLocation_distanceDesc: `Choose a distance from your current location`,
    settingsNotificationLocation_distanceOf: `Distance of`,
    settingsNotificationLocation_distanceTitle: `Distance from you`,
    settingsNotificationLocation_gpsError: `This option cannot be applied because location permissions are off`,
    settingsNotificationLocation_innerDesc: `Send notification from everywhere around your country`,
    settingsNotificationLocation_optionPickerError: `Choose one of the options`,
    settingsNotificationLocation_pickFromListError: `Pick city from list`,
    settingsNotificationQuietHours_timeFrom: `From`,
    settingsNotificationQuietHours_timeTill: `Till`,
    shareAppContent: `A social assistance app 👉🏻 *best that you take a look* 🤩\nA practical way to spread help requests *based on location,* such that someone in the area can see the request. Use it and share it 🙂🙏🏻\n\nLink to the app here 👇🏻👇🏻\nwww.willingapp.com\n\nInvited to download ⬇️ and share ➡️ with others to increase good ✨😇`,
    shareAppSubject: `Sharing Willing`,
    sharePopupTitle: `Share via`,
    shareRequestTitle: `[CategoryType] on Willing:`,
    signup: `Continue to register`,
    skip: `Skip`,
    SMS: `SMS`,
    Social: `Social`,
    start: `START`,
    status: `Status:`,
    status_close: `Close`,
    status_null: `N/A`,
    status_open: `Open`,
    tabBar_myRequests: `Mine`,
    tabBar_requestsByLocation: `Location`,
    tabBar_requestsByRecent: `Recent`,
    telephone_uppercase: `TELEPHONE`,
    termsAcceptDescription: `By clicking \"Continue to register\" I confirm that I have read and I agree to the terms and conditions.`,
    thanks_for_review: `Thank you for your review!`,
    time: `Time posted:`,
    time_daysAgo: `days`,
    time_expiredTime: `Expired`,
    time_hoursAgo: `hours`,
    time_minsAgo: `minutes`,
    time_monthsAgo: `months`,
    time_oneDayAgo: `a day`,
    time_oneHourAgo: `an hour`,
    time_oneMinAgo: `a minute`,
    time_oneMonthAgo: `a month`,
    time_oneWeekAgo: `a week`,
    time_oneYearAgo: `a year`,
    time_pastTime: `ago`,
    time_weeksAgo: `weeks`,
    time_yearsAgo: `years`,
    title: `title`,
    tryAgain: `Try Again`,
    undo: `Undo`,
    unlimited: `Unlimited`,
    urgentLevel_0: `Not urgent`,
    urgentLevel_1: `Moderate`,
    urgentLevel_2: `Serious`,
    urgentLevel_3: `Critical`,
    urgentLevel_4: `Life threatening`,
    urgentLevel_uppercase: `URGENCY LEVEL`,
    validation_description: `Description is too short, you must enter at least 20 charters`,
    validation_location: `Location not valid`,
    validation_shortName: `Name too short, You must enter a valid name`,
    validation_validNumber: `You must enter a valid number`,
    verifyDigits_changeNumber: `Change`,
    verifyDigits_codeDescription: `6-digit code`,
    verifyDigits_description: `Please enter the SMS verification code sent to you:`,
    verifyDigits_errorMessage: `The code you entered is invalid`,
    verifyDigits_resendButton: `send me again`,
    verifyDigits_resendDescription: ` I didn\’t get the code!`,
    verifyDigits_rightNumber: `Right number`,
    verifyDigits_verified: `VERIFIED!`,
    verifyDigits_verify: `VERIFICATION CODE`,
    verifyDigits_verifyFailure: `Verify Failure`,
    verifyPhone_errorMessage: `You need to enter valid phone number`,
    verifyPhone_message: `Please enter your country code and telephone number below.The authentication code will be sent via SMS shortly:`,
    verifyPhone_phoneHint: `Enter phone number`,
    verifyPhone_title: `Verify your telephone number`,
    verifyPhone_verifyMessage: `Are you sure? Please check`,
    version: `Version`,
    welcome: `Welcome to Willing!`,
    whatsAppError: `Something happened and the WhatsApp app could not be opened, the application might not be installed`,
    whatsAppQuestion: `Would you like to send a WhatsApp message to the number for which you posted the request?`,
    when_uppercase: `WHEN`,
    where_uppercase: `WHERE`,
    yes: `Yes`,
    yesDelete: `Yes, delete`,
    app_name: `Willing`,
    app_name_uppercase: `WILLING`,
    settings_languageEng: `English`,
    settings_languageHeb: `עברית`,
};
