export default {
    MOBILE_NUMBER: 'Mobile Number',
    NXT: 'NEXT',
    VERIFICATION_CODE: 'Verification Code',
    ENTER_VERIFICATION_CODE: 'Please enter the SMS verification \ncode sent to you',
    WELCOME_TO_WILLING: 'Welcome To Willing',
    CONGRATS_YOU_VERIFIED: 'Congratulations you’re \nverified!',
    aboutDescription: `אפליקציה חברתית המחברת בין אנשים הזקוקים לעזרה כלשהי לאלה שיכולים לסייע. החיבור באמצעות מנוע חכם המשתמש בפרטים שנמסרו על ידי המשתמשים כדי לייצר התאמות אפקטיביות.`,
    aboutTitle: `אודות Willing`,
    aboutTitleUpperCase: `אודות`,
    appVerErrorMessage: `אופס! נראה שאינך משתמש בגרסה מעודכנת, עדכנ/י את האפליקציה כדי להמשיך בשימוש`,
    call: `התקשר`,
    cancel_uppercase: `בטל`,
    close: `סגור`,
    closeNote: `את/ה בטוח שבצונך לסגור את הבקשה? אם תסגור את הבקשה משתמשים אחרים לא יכלו לראות אותה`,
    contactUs_email: `דואר אלקטרוני`,
    contactUs_EmailHint: `לדוג\':  your@email.com`,
    contactUs_error_email: `יש להכניס כתובת דוא"ל תקינה`,
    contactUs_error_message: `יש לרשום הודעה`,
    contactUs_error_name: `יש להכניס שם מלא`,
    contactUs_error_phone: `יש להכניס מספר טלפון תקין`,
    contactUs_fullName: `שם מלא`,
    contactUs_fullNameHint: `לדוג\': ישראל ישראלי`,
    contactUs_message: `הודעה`,
    contactUs_messageHint: `הכנס תוכן הודעה כאן`,
    contactUs_phone: `טלפון`,
    contactUs_phoneHint: `לדוג\': 0501234567`,
    contactUs_title: `נתקלת בבעיה? יש לך שאלה? סתם בא לך להגיד משהו? אנחנו פה בשבילך (:`,
    contactUsSuccess: `תודה על הודעתך.`,
    defaultMessageForUser: `שלום, ראיתי ב-Willing את ההודעה שלך: \n \n [Desc] \n \n אשמח לראות אם אוכל לסייע בעניין.\nwww.willingapp.com`,
    delete: `מחק`,
    deletedMessage: `הבקשה שלך נמחקה`,
    deleteNote: `את/ה בטוח שאתה/ה רוצה למחוק את הבקשה הזאת? פעולה זאת אינה ניתנת לביטול`,
    description_uppercase: `תיאור`,
    distance_uppercase: `המרחק ממיקומך`,
    dueDate_uppercase:  `יפוג בעוד`,
    edit_lowercase: `ערוך`,
    edit_uppercase: `ערוך`,
    editRequest_title: `עריכת בקשה`,
    Emergency: `חירום`,
    filter_byKeyword: `סינון לפי מילת מפתח`,
    filter_clear: `נקה`,
    filter_missingData: `לא נמצאו בקשות לפי הנתונים שהזנת`,
    filter_pickCategory: `בחר קטגוריה`,
    filter_pickCity: `בחר עיר`,
    filter_title: `סינון`,
    fullImage_image:  `תמונה`,
    fullImage_of:  `מתוך`,
    General:  `כללי`,
    GiveAwayItem:  `חפצים למסירה`,
    gpsDeniedNote:  `לחוויה מלאה של האפליקציה יש לתת הרשאות מיקום`,
    image_pickerOptions:  `בחר אפשרות`,
    image_uppercase:  `תמונה`,
    imageLink_uppercase:  `קישור לתמונה`,
    informationNotAvailable:  `מידע לא זמין`,
    intro_description1:  `בקשו מה שאתם צריכים מהאנשים הרלוונטיים שרוצים לעזור.`,
    intro_description2:  `עזרו לך? כדאי לסגור את הבקשה כדי שלא יפנו אליך יותר.`,
    intro_description3:  `רוצה לעזור בקטנה? אתם בוחרים למי ומתי.`,
    intro_title1:  `קבל/י עזרה`,
    intro_title2:  `יכולת שליטה על הבקשות`,
    intro_title3:  `מיקרו-התנדבות`,
    ItemNeeded:  `דרושים חפצים`,
    location_setLocation:  `הגדר מיקום`,
    location_uppercase:  `מיקום`,
    LostAndFound:  `אבדות ומציאות`,
    Medical:  `רפואי`,
    message:  `הודעה`,
    messageBar_tip1:  `תמיד ניתן לסגור את הבקשה על ידי כניסה  לבקשה שלך ולחיצה על \"סגור\".`,
    messageBar_tip2: `מכירים מישהו שצריך עזרה? תפתחו בקשה בשמם כולל העיר שלהם והטלפון.`,
    messageBar_tip3:  `הידעת? Willing היא ללא מטרות רווח. מוזמנים להתנדב או לתרום. פנו אלינו דרך תפריט הצד.`,
    messageBar_tip4: `תמיד נשמח לקבל הערות או רעיונות לשיפורים - פנו אלינו דרך תפריט הצד.`,
    messageBar_tip5: `בקרוב בWilling: צ\'אט אנונימי, הודעות פוש חכמות, ומנוע סינון חכם. אתם קובעים מתי תקבלו הודעות, איזה סוגים ואיפה.`,
    mineTag:   `שלי`,
    moreInfo:  `פרטים נוספים`,
    name: `שם`,
    name_uppercase: `שם`,
    nav_about: `אודות`,
    nav_faq: `שאלות ותשובות`,
    nav_feedback:  `עזרה/משוב`,
    nav_homeScreen:  `דף הבית`,
    nav_RateUs:  `דרג אותנו`,
    nav_settings:  `הגדרות`,
    nav_Share:  `שיתוף`,
    nav_terms_n_conditions:  `תנאי השימוש והמדיניות`,
    networkErrorMessage:  `אופס! על מנת להשתמש באפליקציה יש צורך בחיבור לאינטרנט`,
    networkErrorTitle:  `אין חיבור`,
    newRequest_categoriesDescription: `נתחיל בבחירת הקטגוריה המתאימה ביותר לתיאור הבקשה שלך. הדבר יעזור לאחרים לראות את הבקשה שלך במהירות.`,
    newRequest_contactDescription: `כמעט סיימנו! נשאר רק להוסיף את הפרטים האישיים שתרצה לשתף עם מי שיראה את הבקשה`,
    newRequest_contactOptionMyDetails: `הפרטים שלי`,
    newRequest_contactOptionSomeoneElse:  `בקשה עבור מישהו אחר`,
    newRequest_contactsPicker: `בחר/י מרשימת אנשי הקשר שלך`,
    newRequest_detailsDescription:  `כעת אנא מלאו פרטים נוספים אודות הבקשה`,
    newRequest_detailsDescriptionHint: `הקלי/י את תיאור הבקשה עם מינימום 20 תווים`,
    newRequest_successMessage:`הבקשה שלך פורסמה בהצלחה`,
    newRequest_successUpdate: `הבקשה שלך עודכנה בהצלחה`,
    newRequest_title: `בקשה חדשה`,
    newRequest_whenDescription: `לכמה זמן תרצה שהבקשה תתפרסם לפני סגירה אוטומטית?`,
    newRequest_whereDescription: `באיזה מרחק מהמיקום שציינת לפרסם את הבקשה?`,
    newRequestLocation:  `מיקום(ברירת מחדל - נוכחי)`,
    next_uppercase: `הבא`,
    no:  `לא`,
    noDataMessage_mine: `עוד לא הוצאת בקשות ולכן המסך ריק, להוצאת בקשה חדשה יש ללחוץ על + למטה.`,
    noPermission: `אין הרשאה`,
    noString: `לא זמין`,
    ok_uppercase: `אשר`,
    phone: `מספר טלפון`,
    phone_uppercase: `מספר טלפון`,
    posted: `התפרסמה לאחרונה`,
    postedForOtherMessage: `שלום, פרסמתי ב Willing את הבקשה שלך:\n\n[fullDesc]\n\n מקווה שיעזור, אם עזרו לך, אז אשמח להתעדכן ואז אסגור את הבקשה באפליקציה.\n\nהאפליקציה נמצאת כאן:   [http://www.willingapp.com] .\nבהצלחה (:`,
    posterName_uppercase: `שם המבקש`,
    report: `דווח כלא ראוי`,
    reportHint: `רשום את ההערה שלך…`,
    reportNote:  `למה הינך רוצה לדווח על הבקשה הזאת כפוגענית?`,
    reportSuccess:  `הדיווח נשלח בהצלחה, תודה על ערנותך`,
    requestDetails_CallTo: `התקשר אל:`,
    requestDetails_CallToError: `לא ניתן להתקשר, חסר מספר`,
    requestDetails_connectionDetails: `ניתן ליצור קשר עם מפרסם הבקשה בדרכים הבאות:`,
    requestDetails_km:  `ק\"מ`,
    requestDetails_meter:  `מ\'`,
    requestDetails_SMSError:  `לא ניתן לשלוח את ההודעה, חסר מספר טלפון.`,
    requestDetails_title:  `פרטי בקשה`,
    requestDetails_whatsApp: `וואטסאפ`,
    requestLink_uppercase:  `קישור לבקשה`,
    RideDeliver:  `נסיעה/העברה`,
    RoadAssist:  `עזרה בדרך`,
    send:  `שלח`,
    sendFailure:  `משהו קרה, הבקשה שלך לא נשלחה, נסה שנית.`,
    serverConnectionErrorMessage:  `אופס! נראה שיש בעיות בשרת, יש לנסות שוב במאוחר יותר`,
    settings_language:  `שפה`,
    settingsNotification:  `הגדרות התראות`,
    settingsNotification_addToList:  `הוסף לרשימה`,
    settingsNotification_category: `קטגוריה`,
    settingsNotification_categoryDesc:  `כל הקטגוריות`,
    settingsNotification_categoryError: `בקשות חירום לא ניתן לנטרל`,
    settingsNotification_categoryInnerDesc: `בחר באילו קטגוריות תרצה לקבל התראות`,
    settingsNotification_emptyAppendError:  `יש לרשום בשדה המתאים`,
    settingsNotification_keywords: `מילות מפתח`,
    settingsNotification_keywordsAppendError: `מילת המפתח קיימת ברשימה`,
    settingsNotification_keywordsDesc: `הגדר/י התראות לפי מילות מפתח`,
    settingsNotification_keywordsHint: `הכנס מילת מפתח`,
    settingsNotification_keywordsInnerDesc: `שלח התראה במידה והמילים הבאות מופיעות בתוך הבקשה`,
    settingsNotification_location: `מיקום`,
    settingsNotification_locationDesc: `מכל מקום`,
    settingsNotification_main: `אפשר התראות`,
    settingsNotification_mainDesc: `שלח התראות עבור בקשות חדשות`,
    settingsNotification_quietHours: `שעות שקטות`,
    settingsNotification_quietHoursDesc: `הגדר/י שעות שבהם לא יתקבלו התראות`,
    settingsNotificationLocation_alsoFrom: `וגם מ`,
    settingsNotificationLocation_cityAppendError: `העיר קיימת ברשימה`,
    settingsNotificationLocation_cityDesc: `הכנס שם עיר שממנה תרצה לקבל התראות`,
    settingsNotificationLocation_cityHint: `הכנס שם עיר`,
    settingsNotificationLocation_cityTitle: `עיר ספציפית`,
    settingsNotificationLocation_distanceDesc: `בחר מרחק ממיקומך הנוכחי`,
    settingsNotificationLocation_distanceOf:  `מרחק של`,
    settingsNotificationLocation_distanceTitle: `מרחק ממך`,
    settingsNotificationLocation_gpsError: `לא ניתן לממש אופציה זאת כיוון שהרשאות מיקום כבויות`,
    settingsNotificationLocation_innerDesc: `שלח התראה מכל מקום ברחבי המדינה שלך`,
    settingsNotificationLocation_optionPickerError: `יש לבחור אחד מהאפשרויות`,
    settingsNotificationLocation_pickFromListError: `יש לבחור עיר מהרשימה`,
    settingsNotificationQuietHours_timeFrom: `משעה`,
    settingsNotificationQuietHours_timeTill: `עד`,
    shareAppContent: `אפליקציית עזרה חברתית 👈🏻 *הכי פשוט שתסתכלו* 🤩\nאמצעי הפצה של עזרה נטו *מבוסס מיקום* כך שמי שנמצא בסביבה ייראה את הפרסום. להשתמש ולהפיץ 🙂🙏🏻\n\nלינק לאפליקציה כאן 👇🏻👇🏻\nhttp://www.willingapp.com\n\nמוזמנים להוריד  ⬇️ וגם לשתף ⬅️ אחרים  להרבות הטוב✨😇`,
    shareAppSubject:  `שיתוף אפליקציית Willing`,
    sharePopupTitle: `שתף באמצעות`,
    shareRequestTitle: `[CategoryType] ב-Willing:`,
    signup: `המשך לרישום`,
    skip:  `דלג`,
    SMS: `סמס`,
    Social:  `חברתי`,
    start: `התחל`,
    status: `סטטוס:`,
    status_close: `סגור`,
    status_null: `לא זמין`,
    status_open: `פתוח`,
    tabBar_myRequests: `שלי`,
    tabBar_requestsByLocation: `בסביבה`,
    tabBar_requestsByRecent: `אחרונים`,
    telephone_uppercase: `טלפון`,
    termsAcceptDescription: `בלחיצה על \"המשך לרישום\" אני מאשר/ת כי קראתי את תנאי השימוש והמדיניות של Willing והם מוסכמים עלי.`,
    thanks_for_review: `תודה על הדירוג!`,
    time: `מועד הפרסום:`,
    time_daysAgo:  `ימים`,
    time_expiredTime: `לא בתוקף`,
    time_hoursAgo: `שעות`,
    time_minsAgo: `דקות`,
    time_monthsAgo: `חודשים`,
    time_oneDayAgo: `יום`,
    time_oneHourAgo: `שעה`,
    time_oneMinAgo:  `דקה`,
    time_oneMonthAgo:  `חודש`,
    time_oneWeekAgo:  `שבוע`,
    time_oneYearAgo: `שנה`,
    time_pastTime: `לפני`,
    time_weeksAgo: `שבועות`,
    time_yearsAgo: `שנים`,
    title: `כותרת`,
    tryAgain: `נסה שוב`,
    undo: `בטל`,
    unlimited: `ללא הגבלה`,
    urgentLevel_0: `לא דחוף`,
    urgentLevel_1: `חשוב`,
    urgentLevel_2: `דחוף`,
    urgentLevel_3: `דחוף מאוד`,
    urgentLevel_4: `מציל חיים`,
    urgentLevel_uppercase: `רמת דחיפות`,
    validation_description: `תיאור קצר מידי, יש לכתוב לפחות 20 תווים`,
    validation_location: `מיקום לא תקין`,
    validation_shortName: `שם קצר מידי, יש לרשום שם תקין`,
    validation_validNumber: `חובה להזין מספר תקין`,
    verifyDigits_changeNumber: `לשנות`,
    verifyDigits_codeDescription: `קוד בן 6 ספרות`,
    verifyDigits_description: `אנא הקש את המספר שקיבלת`,
    verifyDigits_errorMessage: `הקוד שהכנסת אינו תקין`,
    verifyDigits_resendButton: `שלח שוב`,
    verifyDigits_resendDescription: `לא קיבלתי את הקוד`,
    verifyDigits_rightNumber:  `מספר תקין`,
    verifyDigits_verified: `אומת!`,
    verifyDigits_verify: `אימות קוד`,
    verifyDigits_verifyFailure: `אימות נכשל`,
    verifyPhone_errorMessage: `הקש מספר טלפון תקף`,
    verifyPhone_message: `אנא הקש את אזור החיוג ומספר טלפון. קוד האימות ישלח אליך בסמס ברגעים הקרובים.`,
    verifyPhone_phoneHint: `הכנס מספר טלפון`,
    verifyPhone_title: `אנא אשר/י את מספר הטלפון שלך`,
    verifyPhone_verifyMessage: `האם את/ה בטוח/ה? אנא בדק/י שנית`,
    version: `גרסה`,
    welcome: `ברוכים הבאים ל-Willing!`,
    whatsAppError: `משהו קרה ולא ניתן לפתוח את אפליקציית WhatsApp, יכול להיות שהאפליקציה לא מותקנת.`,
    whatsAppQuestion: `האם תרצה לשלוח הודעת WhatsApp למספר שבשבילו פירסמת את הבקשה?`,
    when_uppercase: `מתי?`,
    where_uppercase: `היכן?`,
    yes: `כן`,
    yesDelete: `כן, מחק`,
    app_name: `Willing`,
    app_name_uppercase: `WILLING`,
    settings_languageEng: `English`,
    settings_languageHeb: `עברית`,
};