export default {
    LOGIN:"LOGIN",
    LOGOUT:'LOGOUT',
    PROFILE:'PROFILE',
    LOADER:'LOADER',
    CHECKINTERNET:'CHECKINTERNER',
    IS_FIRST_TIME:"IS_FIRST_TIME",
    SET_TAB:"SET_TAB",
    ACCOUNT_MODAL:"ACCOUNT_MODAL",
    USER_TYPE:"USER_TYPE",
    LANGUAGE:'LANGUAGE'
}